version: "3.8"

services:
  postgresdb:
    image: "postgis/postgis:14-3.2"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - pgdb:/var/lib/postgresql/data
  mongodb:
    image: "mongo:5.0.9"
    restart: always
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mgdb:/data/db
    #mongo_seed:
    #image: "mongo:5.0.9"
    #links:
    #  - mongodb
    #volumes:
    #  - ./seed:/seed
    #command:
    #  /seed/mongodb/import.sh
  app:
    depends_on:
      - postgresdb
      - mongodb
    build: ./bbdd2PromocionApp
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    environment:
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.spatial.dialect.postgis.PostgisDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.spatial.dialect.postgis.PostgisDialect
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.spatial.dialect.postgis.PostgisDialect
      - HIBERNATE_DIALECT=org.hibernate.spatial.dialect.postgis.PostgisDialect
      - SPRING_JPA_HIBERNATE_SHOW_SQL=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE?useSSL=false
      - SPRING_DATASOURCE_USERNAME=$POSTGRESDB_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRESDB_PASSWORD
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=$MONGODB_DOCKER_PORT
      - SPRING_DATA_MONGODB_DATABASE=$MONGODB_DATABASE
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_BATCH_JOB_ENABLED=false
      - SPRING_BATCH_INITIALIZE_SCHEMA=always
      - SPRING_BATCH_JDBC.INITIALIZE_SCHEMA=always
    stdin_open: true
    tty: true

volumes:
  pgdb:
  mgdb:
